spring.application.name=patient-service

# Enables the H2 database web console
# You can access it from:
# http://localhost:4000/h2-console
spring.h2.console.path=/h2-console

# JDBC URL used to connect to the H2 database
# "mem:testdb" means an in-memory database
# Data disappears when the application stops
spring.datasource.url=jdbc:h2:mem:testdb

# JDBC driver used to communicate with H2
spring.datasource.driver-class-name=org.h2.Driver

# Database username
spring.datasource.username=admin_viewer

# Database password
spring.datasource.password=password

# Hibernate dialect for H2 database
# Tells Hibernate which SQL syntax to generate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Controls schema generation
# update = create tables if missing and update existing ones
spring.jpa.hibernate.ddl-auto=update

# Always execute SQL initialization scripts
# such as schema.sql or data.sql if they exist
spring.sql.init.mode=always

# Run the application on port 4000
# instead of the default 8080
server.port=4000

logging.level.root=info