# The name of the Docker Compose environment.
name: devtiro-build-task-app
services:
  # The UI service.
  ui:
    # Build the UI image from the source in the frontend directory.
    build: ./frontend
    ports:
      # Make the UI available on http://localhost:3000
      - '3000:3000'
    # Tell the UI how to find your Spring Boot app.
    environment:
      - BACKEND_HOST=host.docker.internal
      - BACKEND_PORT=8080
    # For Linux compatibility
    extra_hosts:
      - 'host.docker.internal:host-gateway'